### ISSUE TITLE
Thumbnails not created

### ISSUE THREAD

**Issue by defish1962** [yinlinchen/thumbnail_creator#1]
I've deployed the thumbnail creator application from the Serverless App repository (along with the required layers). The S3 buckets were created but nothing happens when I upload an image or PDF file to the upload bucket. Nothing gets created in the results bucket. 

Is there an additional step that is needed after the app is deployed?

**Comment by defish1962** [comment]
This error shows in the logs: 

[ERROR] Runtime.ImportModuleError: Unable to import module 'app': No module named 'filetype' Traceback (most recent call last):

**Comment by yinlinchen** [comment]
Please check if your lambda function contains FileTypeUtils layer, like the one below.
<img width="884" alt="Screen Shot 2023-03-18 at 12 52 02 PM" src="https://user-images.githubusercontent.com/7999195/226121204-ddf37425-8a6c-4e83-afd5-bbb7b11fd768.png">
